### ISSUE TITLE
Question about kpi page

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/docs-monitoring#153]
I have some docs questions.. not sure who is the best person to ask, so just post it here.

## [gorouter.total_routes](https://docs.pivotal.io/pivotalcf/2-4/monitoring/kpi.html#number-of-gorouter-routes-registered)

The recommanded measurement says `5-minute average of the per second delta`,
but the metrics is emitted per `30s`. How to calculate the `per second delta`?

---
## [number-of-route-registration-messages-sent-and-received](https://docs.pivotal.io/pivotalcf/2-4/monitoring/kpi.html#number-of-gorouter-routes-registered)

The recommanded measurement:
> Difference of 5-minute average of the per second deltas for `gorouter.registry_message.route-emitter` and sum of `route_emitter.HTTPRouteNATSMessagesEmitted` for all Route Emitters

is hard to understand and misleading depending on interpretation...

Does it mean:
1.
```
5minAvg(perSecDelta(gorouter.registry_message.route-emitter)) 
-
5minAvg(sum(route_emitter.HTTPRouteNATSMessagesEmitted))
```
Or,
2.
```
5minAvg(  
  perSec(
    gorouter.registry_message.route-emitter
    -
    sum(route_emitter.HTTPRouteNATSMessagesEmitted)
  )
)
```

From the text description provided for this metrics, the second formula makes
more sense to me. But when I read the recommended measurement, I interpreted
the first formula as I understand. The text representation for the second
formula should be somehting like:
> 5-minute average of the per second difference between
`gorouter.registry_message.route-emitter` and the sum of
`route_emitter.HTTPRouteNATSMessagesEmitted` for all Route Emitters

But even the second formula is not practical, given the metrics frequency is
`with each event`.

---

Not sure both of the questions are relevent though, happy to have a discussion.

**Comment by fredwangwang** [comment]
Close for inactivity

**Comment by mlimonczenko** [comment]
Hi, @fredwangwang. Sorry about the inactivity. The best place is to contact us in our slack channel, #pcf-docs.
